version: '3.9'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: fabio123
    ports:
      - "5432:5432"
    volumes:
      - postgres_v:/var/lib/postgresql/data

  redis:
    image: redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass '__@picker-redis'
    ports:
      - "6379:6379"
    volumes:
      - redis_v:/data
